kumuluzee:
  name: ehive
  version: 1.0.0
  env:
    name: dev
  server:
#    base-url: http://localhost:8081
    base-url: 83.212.82.142:8081
    http:
      port: 8081
  datasources:
  - jndi-name: jdbc/EhiveDS
    connection-url: jdbc:postgresql://localhost:5432/pkp
    username: postgres
    password: PGpostgres
    max-pool-size: 20